### ISSUE TITLE
Calculator with HTML , CSS , JS ( Responsive ) 

### ISSUE THREAD

**Issue by charann29** [charann29/HacktoberFest2023#1]

**Comment by krishprav** [comment]
@charann29 i am interested.

**Comment by charann29** [comment]
How about you do the first issue I assigned you on first, and then if no one else has claimed this one I can assign you too.
These are relatively simple issues and I would hope for some other people to learn about contributing as well.

Please consider giving a star to the repo!

**Comment by AkashKMathew** [comment]
Hey @charann29, I would like to work on this issue. Please assign to me.

**Comment by charann29** [comment]
Yeah @AkashKMathew , You can work on it now..

Looking forward to see your PR!
