### ISSUE TITLE
Create an image slider that cycles through a set of images.

### ISSUE THREAD

**Issue by charann29** [charann29/HacktoberFest2023#11]

**Comment by devmusiczz** [comment]
Hey @charann29 can you assign this issue to me? I am new to open source and want to contribute, also can I make the slider using simple HTML, CSS and JS or any specific tech stack?

**Comment by charann29** [comment]
You can contribute now , looking forward to see your PR.

**Comment by devmusiczz** [comment]
can I make the slider using simple HTML, CSS and JS or any specific tech stack?

**Comment by charann29** [comment]
@devmusiczz Yeahh!
