### ISSUE TITLE
Build a simple blog website with multiple articles and a clean layout.

### ISSUE THREAD

**Issue by charann29** [charann29/HacktoberFest2023#2]
Tag me if you interested.

**Comment by sharadj34** [comment]
Hey! @charann29 I have my portfolio website which contains my blog page. Kindly refer to that on : https://sharadj34.github.io/Portfolio/

**Comment by charann29** [comment]
@sharadj34 Would be great if you can create  a PR with the code.

Looking forward see your PR.
